### ISSUE TITLE
Plugin non compatible avec Keycloak 23.0.6

### ISSUE THREAD

**Issue by jychp** [ansforge/keycloak-prosanteconnect#26]
Il semblerait que le plugin ne soit pas compatible avec la version 23.0.6 de Keycloak.

Comment reproduire :
```
docker run --rm -v $HOME/keycloak/providers/:/opt/keycloak/providers/ -p 8080:8080 -e KC_HTTP_RELATIVE_PATH=/auth -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:23.0.6 start-dev
```

Stack trace :
```
Updating the configuration and installing your custom providers, if any. Please wait.
2024-03-08 15:26:07,373 WARN  [org.keycloak.services] (build-25) KC-SERVICES0047: psc-user-attribute-mapper (fr.ans.keycloak.mappers.ProSanteConnectUserAttributeMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice
2024-03-08 15:26:07,374 WARN  [org.keycloak.services] (build-25) KC-SERVICES0047: psc-username-template-mapper (fr.ans.keycloak.mappers.ProSanteConnectUsernameTemplateMapper) is implementing the internal SPI identity-provider-mapper. This SPI is internal and may change without notice
2024-03-08 15:26:07,611 WARN  [org.keycloak.services] (build-25) KC-SERVICES0047: psc (fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProviderFactory) is implementing the internal SPI social. This SPI is internal and may change without notice
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:321)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:696)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:269)
	... 12 more

ERROR: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor#setupEndpoints threw an exception: java.lang.RuntimeException: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:321)
	at io.quarkus.resteasy.reactive.server.deployment.ResteasyReactiveProcessor.setupEndpoints(ResteasyReactiveProcessor.java:696)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'
	at org.jboss.resteasy.reactive.common.processor.EndpointIndexer.createEndpoints(EndpointIndexer.java:269)
	... 12 more

ERROR: jakarta.enterprise.inject.spi.DeploymentException: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'
ERROR: Non static nested resources classes are not supported: 'fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider$OIDCEndpoint'

```

**Comment by jothoma1** [comment]
Même erreur avec un keycloak-24.0.1

**Comment by jychp** [comment]
Seems to be fixed by https://github.com/ansforge/keycloak-prosanteconnect/pull/27

**Comment by guillaumebesse** [comment]
Le problème ne semble pas fixé.
J'ai la même erreur que @jychp avec la toute dernière version du code (keycloak-prosanteconnect-3.0.3-SNAPSHOT.jar) et keycloak 23.0.1. 
Le commit qui devait fixer le pb a été annulé.

**Comment by jothoma1** [comment]
Oui le pb n'est pas fixé, est il prévu de faire une nouvelle release ?

**Comment by guillaumebesse** [comment]
J'ai essayé avec le code sans le dernier commit qui annule les modif mais ca ne marche pas.

**Comment by cpanissod** [comment]
Pourriez-vous essayer avec la release 4.0.0 ?

**Comment by guillaumebesse** [comment]
> Pourriez-vous essayer avec la release 4.0.0 ?

@cpanissod J'ai fait le test. Je n'ai pas plus le message d'erreur. Par contre, dans les Identity Providers je ne retrouve pas Pro Santé Connect. Est-ce normal ?

**Comment by guillaumebesse** [comment]
Autant pour moi, j'ai merdu. Ca marche, je le vois bien Pro Santé Connect en tant que identity providers. 
Je vais poursuivre mon intégration. 
Merci.

**Comment by aparrot89** [comment]
https://github.com/ansforge/keycloak-prosanteconnect/releases/tag/keycloak-prosanteconnect-4.0.0
@cpanissod 
Cette release ajoute aussi la compatibilité avec keycloak 24 ?

**Comment by cpanissod** [comment]
Bonjour, à date, je n'ai que testé le démarrage d'une instance KC 24 avec le provider. Je n'ai pas eu d'erreur. Et le démarrage d'un flow d'authentification se fait également.

**Comment by aparrot89** [comment]
Ca marche merci !!
