### ISSUE TITLE
Uncaught server error on KC 25.0.1

### ISSUE THREAD

**Issue by Cubox** [ansforge/keycloak-prosanteconnect#29]
```
2024-07-01 14:59:40,508 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.lang.NoSuchMethodError: 'void org.keycloak.broker.provider.BrokeredIdentityContext.<init>(java.lang.String)'
        at fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider.extractIdentity(ProSanteConnectIdentityProvider.java:317)
        at org.keycloak.broker.oidc.OIDCIdentityProvider.getFederatedIdentity(OIDCIdentityProvider.java:396)
        at fr.ans.keycloak.providers.prosanteconnect.ProSanteConnectIdentityProvider.getFederatedIdentity(ProSanteConnectIdentityProvider.java:189)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint.authResponse(AbstractOAuth2IdentityProvider.java:557)
        at org.keycloak.broker.oidc.AbstractOAuth2IdentityProvider$Endpoint$quarkusrestinvoker$authResponse_ab908fbdd086ee82e140d8a818c077362a2d04b4.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

Sur Keycloak 25.0.1, en bac à sable.

**Comment by cpanissod** [comment]
OpenJDK 17 est désormais obsolète sur Keycloak 25. Cette release ajoute le support d'OpenJDK 21.

**Comment by cpanissod** [comment]
@Cubox 
Resolved with last release [keycloak-prosanteconnect-5.0.0](https://github.com/ansforge/keycloak-prosanteconnect/releases/tag/keycloak-prosanteconnect-5.0.0)
